import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins", // optional CSS variable
  subsets: ["latin"],
  weight: ["400", "500", "700"], // specify the weights you need
});

export const metadata: Metadata = {
  title: "Befer - Professional Tools For Service Providers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}